---

name: beetle_feeding_damage
version: 0.1.0
authors:
  - Matthew Hartley
  - Tjelvar Olsson
start: 2017-05-04
end: sometime
container: beetle_feeding_damage-development
dataset: initial_sample_data
